### ISSUE TITLE
Subscriber: Handle temp-filepath

### ISSUE THREAD

**Issue by kvold** [kartverket/geosynkronisering#107]
Subscriber needs to be able to correctly find the temp-folder on both windows and linux.

Can use Path.GetTempPath, but it only checks the TMPDIR-env on linux, and that could be empty.

**Comment by jarped** [comment]
I tested this on a centos-container and it wrote to /tmp even if it reported nothing for $TMPDIR:
![image](https://user-images.githubusercontent.com/3570752/83133373-121afb80-a0e3-11ea-84ed-d7fddbbb71d6.png)

**Comment by kvold** [comment]
Good! There's still the problem that /tmp is often mount on the system-disk though, so a user have to be aware that it might fill up quickly. And they have to then change the temp-variable, be it on windows or linux

**Comment by jarped** [comment]
Handled through overriding temp-file location
